### ISSUE TITLE
Program loads blank when server status page is down.

### ISSUE THREAD

**Issue by DazzaJay** [arzynik/wowstat#15]
Unsure if the Server Status page being offline has anything to do with it, but I figured I'd add that info.

To reproduce this issue, this is what I did:

Played WoW till the servers went down.
Thought "I wonder if there's an app that will notify me when they are back up"
Found this app, downloaded and installed.
First run.
App goes "Not Responding" for about 60 seconds, (See first screenshot)
App then unfreezes, gets a background texture, and that's all. nothing more (Screenshot 2)

At best guess (As I'm not a programmer) I'm guessing it can't handle the Server Status page being down?

![1](https://cloud.githubusercontent.com/assets/3713158/6798974/35f91164-d266-11e4-9de4-849dc39b056e.jpg)
![2](https://cloud.githubusercontent.com/assets/3713158/6798975/3686c630-d266-11e4-80ac-0bca98e4bd5d.jpg)

**Comment by DazzaJay** [comment]
Maybe not.....
ServerStatus page is back online. reloading WoW Stat shows the same issue. blank window.

**Comment by arzynik** [comment]
resolved in https://github.com/arzynik/wowstat/releases/tag/3.0.2
